---
version: "3"

services:
  sip:
    image: ghcr.io/vanegmondgroep/sip:2.0.1
    restart: always
    ports:
      - "${APP_HTTP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    volumes:
      - "sip:/home/runtime/public/storage"
      - "backup:/opt/vanegmond/backup"
      - "./.env:/home/runtime/public/.env"
      - "./runtime.yml:/opt/runtime/config/runtime.yml:ro"
      - "./backups:/opt/vanegmond/backups"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: "docker.io/bitnami/mariadb:10.5"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD:-supersecret}"
      MARIADB_DATABASE: "${DB_DATABASE:-sip}"
      MARIADB_USER: "${DB_USERNAME:-vanegmond}"
      MARIADB_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "mysql:/bitnami/mariadb"
      - "backup:/opt/vanegmond/backup"
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    image: "docker.io/bitnami/redis:6.2"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  # Proxy not posible yet: https://github.com/influxdata/influxdb/issues/15721
  influxdb:
    image: "influxdb:2.0.4"
    restart: always
    ports:
      - ${APP_INFLUXDB_PORT:-8086}:8086
    volumes:
      - "influxdb:/var/lib/influxdb2"
      - "backup:/opt/vanegmond/backup"

  grafana:
    image: "ghcr.io/vanegmondgroep/grafana:1.0.0"
    restart: always
    volumes:
      - "grafana:/var/lib/grafana/data"
      - "backup:/opt/vanegmond/backup"

  node-red:
    image: ghcr.io/vanegmondgroep/node-red:1.0.0
    restart: always
    volumes:
      - "node-red:/data"
      - "backup:/opt/vanegmond/backup"

  phpmyadmin:
    image: "docker.io/bitnami/phpmyadmin:5"
    restart: always
    environment:
      DATABASE_HOST: mysql
      PHP_UPLOAD_MAX_FILESIZE: 2G
      PHPMYADMIN_ABSOLUTE_URI: "/svc/phpmyadmin/"

  mailhog:
    image: "mailhog/mailhog:latest"
    restart: always

volumes:
  sip:
    driver: local
  mysql:
    driver: local
  influxdb:
    driver: local
  grafana:
    driver: local
  node-red:
    driver: local
  backup:
    driver: local
