---
version: "3"

services:
  sip:
    image: ghcr.io/vanegmondgroep/sip:2.0.1
    deploy:
        resources:
            limits:
              memory: 1024M
            reservations:
              memory: 256M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - "${APP_HTTP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    volumes:
      - "sip:/home/runtime/public/storage"
      - "./.env:/home/runtime/public/.env"
      - "./runtime.yml:/opt/runtime/config/runtime.yml:ro"
      - "./data:/opt/stack/data"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: "docker.io/bitnami/mariadb:10.5"
    deploy:
        resources:
            limits:
              memory: 128M
            reservations:
              memory: 64M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD:-supersecret}"
      MARIADB_DATABASE: "${DB_DATABASE:-sip}"
      MARIADB_USER: "${DB_USERNAME:-vanegmond}"
      MARIADB_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "mysql:/bitnami/mariadb"
      - "./data:/opt/stack/data"
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    image: "docker.io/bitnami/redis:6.2"
    deploy:
        resources:
            limits:
              memory: 128M
            reservations:
              memory: 64M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  # Proxy not posible yet: https://github.com/influxdata/influxdb/issues/15721
  influxdb:
    image: "influxdb:2.0.4"
    deploy:
        resources:
            limits:
              memory: 512M
            reservations:
              memory: 256M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - ${APP_INFLUXDB_PORT:-8086}:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:?}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:?}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME:?}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:?}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:?}
    volumes:
      - "influxdb:/var/lib/influxdb2"
      - "./data:/opt/stack/data"
      - "./config:/opt/stack/config"

  grafana:
    image: "ghcr.io/vanegmondgroep/grafana:1.0.0"
    deploy:
        resources:
            limits:
              memory: 128M
            reservations:
              memory: 64M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    volumes:
      - "grafana:/var/lib/grafana/data"
      - "./data:/opt/stack/data"

  node-red:
    image: ghcr.io/vanegmondgroep/node-red:1.0.0
    deploy:
        resources:
            limits:
              memory: 256M
            reservations:
              memory: 128M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    volumes:
      - "node-red:/data"
      - "./data:/opt/stack/data"

  phpmyadmin:
    image: "docker.io/bitnami/phpmyadmin:5"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      DATABASE_HOST: mysql
      PHP_UPLOAD_MAX_FILESIZE: 2G
      PHPMYADMIN_ABSOLUTE_URI: "/svc/phpmyadmin/"

  mailhog:
    image: "mailhog/mailhog:latest"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  sip:
    driver: local
  mysql:
    driver: local
  influxdb:
    driver: local
  grafana:
    driver: local
  node-red:
    driver: local
